CREATE TABLE [dbo].[mp_saved_search] (
    [saved_search_id]            INT            IDENTITY (1, 1) NOT NULL,
    [contact_id]                 INT            NOT NULL,
    [search_filter_name]         VARCHAR (250)  NULL,
    [keyword]                    VARCHAR (250)  NULL,
    [part_category_id]           NVARCHAR (MAX) NULL,
    [post_process_id]            NVARCHAR (MAX) NULL,
    [material_id]                NVARCHAR (MAX) NULL,
    [buyer_location_id]          NVARCHAR (MAX) NULL,
    [country_id]                 NVARCHAR (MAX) NULL,
    [region_id]                  NVARCHAR (MAX) NULL,
    [proximity_id]               VARCHAR (100)  NULL,
    [geometry_id]                INT            NULL,
    [unit_of_measure_id]         INT            NULL,
    [tolerance_id]               VARCHAR (100)  NULL,
    [width_min]                  FLOAT (53)     NULL,
    [width_max]                  FLOAT (53)     NULL,
    [height_min]                 FLOAT (53)     NULL,
    [height_max]                 FLOAT (53)     NULL,
    [depth_min]                  FLOAT (53)     NULL,
    [depth_max]                  FLOAT (53)     NULL,
    [length_min]                 FLOAT (53)     NULL,
    [length_max]                 FLOAT (53)     NULL,
    [diameter_min]               FLOAT (53)     NULL,
    [diameter_max]               FLOAT (53)     NULL,
    [is_daily_notification]      BIT            NULL,
    [created_on]                 DATETIME       DEFAULT (getdate()) NOT NULL,
    [modified_on]                DATETIME       NULL,
    [status_id]                  SMALLINT       NULL,
    [volume]                     FLOAT (53)     NULL,
    [is_my_capabilities_created] BIT            DEFAULT ((0)) NULL,
    [is_default]                 BIT            DEFAULT ((0)) NULL,
    [IsLargePart]                BIT            NULL,
    [BuyerIndustryId]            NVARCHAR (MAX) NULL,
    [certificate_ids]            NVARCHAR (MAX) DEFAULT ('') NULL,
    CONSTRAINT [pk_mp_saved_search_saved_search_id_contact_id] PRIMARY KEY CLUSTERED ([saved_search_id] ASC, [contact_id] ASC) WITH (FILLFACTOR = 90),
    FOREIGN KEY ([status_id]) REFERENCES [dbo].[mp_mst_status] ([status_id])
);

