CREATE TABLE [dbo].[SalesloftCadences] (
    [salesloft_cadence_id]      INT            IDENTITY (1, 1) NOT NULL,
    [id]                        INT            NOT NULL,
    [created_at]                DATETIME       NULL,
    [updated_at]                DATETIME       NULL,
    [archived_at]               DATETIME       NULL,
    [team_cadence]              BIT            NULL,
    [shared]                    BIT            NULL,
    [remove_bounces_enabled]    BIT            NULL,
    [remove_replies_enabled]    BIT            NULL,
    [opt_out_link_included]     BIT            NULL,
    [draft]                     BIT            NULL,
    [cadence_framework_id]      INT            NULL,
    [cadence_function]          VARCHAR (1000) NULL,
    [name]                      VARCHAR (1000) NULL,
    [tags]                      VARCHAR (1000) NULL,
    [creator_id]                INT            NULL,
    [owner_id]                  INT            NULL,
    [bounced_stage_id]          INT            NULL,
    [replied_stage_id]          INT            NULL,
    [added_stage_id]            INT            NULL,
    [finished_stage_id]         INT            NULL,
    [cadence_priority_id]       INT            NULL,
    [cadence_people_count]      INT            NULL,
    [people_acted_on_count]     INT            NULL,
    [target_daily_people_count] INT            NULL,
    [meetings_booked]           INT            NULL,
    [opportunities_created]     INT            NULL,
    CONSTRAINT [PK_SalesloftCadences_Salesloft_Cadence_Id] PRIMARY KEY CLUSTERED ([salesloft_cadence_id] ASC)
);

