CREATE TABLE [dbo].[SalesloftPeople] (
    [id]                             INT            NOT NULL,
    [created_at]                     DATETIME       NULL,
    [updated_at]                     DATETIME       NULL,
    [last_contacted_at]              DATETIME       NULL,
    [last_replied_at]                DATETIME       NULL,
    [first_name]                     VARCHAR (500)  NULL,
    [last_name]                      VARCHAR (500)  NULL,
    [display_name]                   VARCHAR (500)  NULL,
    [email_address]                  VARCHAR (500)  NULL,
    [full_email_address]             VARCHAR (500)  NULL,
    [secondary_email_address]        VARCHAR (500)  NULL,
    [personal_email_address]         VARCHAR (500)  NULL,
    [phone]                          VARCHAR (500)  NULL,
    [phone_extension]                VARCHAR (500)  NULL,
    [home_phone]                     VARCHAR (500)  NULL,
    [mobile_phone]                   VARCHAR (500)  NULL,
    [linkedin_url]                   VARCHAR (500)  NULL,
    [title]                          VARCHAR (500)  NULL,
    [city]                           VARCHAR (500)  NULL,
    [state]                          VARCHAR (500)  NULL,
    [country]                        VARCHAR (500)  NULL,
    [work_city]                      VARCHAR (500)  NULL,
    [work_state]                     VARCHAR (500)  NULL,
    [work_country]                   VARCHAR (500)  NULL,
    [crm_url]                        VARCHAR (500)  NULL,
    [crm_id]                         VARCHAR (500)  NULL,
    [crm_object_type]                VARCHAR (500)  NULL,
    [owner_crm_id]                   VARCHAR (500)  NULL,
    [person_company_name]            VARCHAR (500)  NULL,
    [person_company_website]         VARCHAR (500)  NULL,
    [person_company_industry]        VARCHAR (500)  NULL,
    [do_not_contact]                 BIT            NULL,
    [bouncing]                       BIT            NULL,
    [locale]                         VARCHAR (500)  NULL,
    [eu_resident]                    BIT            NULL,
    [personal_website]               VARCHAR (500)  NULL,
    [twitter_handle]                 VARCHAR (500)  NULL,
    [last_contacted_type]            VARCHAR (500)  NULL,
    [job_seniority]                  VARCHAR (500)  NULL,
    [custom_fields]                  VARCHAR (1000) NULL,
    [tags]                           VARCHAR (1000) NULL,
    [contact_restrictions]           VARCHAR (500)  NULL,
    [counts]                         VARCHAR (1000) NULL,
    [account_id]                     INT            NOT NULL,
    [owner_id]                       INT            NULL,
    [last_contacted_by_id]           INT            NULL,
    [import_id]                      INT            NULL,
    [person_stage_id]                INT            NULL,
    [most_recent_cadence_id]         INT            NULL,
    [last_completed_step_cadence_id] INT            NULL,
    [last_completed_step_id]         INT            NULL,
    [is_hubspot_id_missing]          BIT            NULL,
    CONSTRAINT [PK_SalesloftPeople_ID] PRIMARY KEY CLUSTERED ([id] ASC)
);

