CREATE TABLE [dbo].[SalesloftUsers] (
    [id]                                      INT            NOT NULL,
    [guid]                                    VARCHAR (1000) NULL,
    [created_at]                              DATETIME       NULL,
    [updated_at]                              DATETIME       NULL,
    [name]                                    VARCHAR (500)  NULL,
    [first_name]                              VARCHAR (500)  NULL,
    [last_name]                               VARCHAR (500)  NULL,
    [job_role]                                VARCHAR (500)  NULL,
    [active]                                  BIT            NULL,
    [time_zone]                               VARCHAR (500)  NULL,
    [slack_username]                          VARCHAR (500)  NULL,
    [twitter_handle]                          VARCHAR (500)  NULL,
    [email]                                   VARCHAR (500)  NULL,
    [email_client_email_address]              VARCHAR (500)  NULL,
    [sending_email_address]                   VARCHAR (500)  NULL,
    [from_address]                            VARCHAR (500)  NULL,
    [full_email_address]                      VARCHAR (500)  NULL,
    [bcc_email_address]                       VARCHAR (500)  NULL,
    [email_signature]                         VARCHAR (5000) NULL,
    [email_signature_type]                    VARCHAR (500)  NULL,
    [email_signature_click_tracking_disabled] BIT            NULL,
    [team_admin]                              BIT            NULL,
    [local_dial_enabled]                      BIT            NULL,
    [click_to_call_enabled]                   BIT            NULL,
    [email_client_configured]                 BIT            NULL,
    [crm_connected]                           BIT            NULL,
    [external_feature_flags]                  VARCHAR (1000) NULL,
    [private_fields]                          VARCHAR (500)  NULL,
    [phone_client_id]                         INT            NULL,
    [phone_number_assignment_id]              INT            NULL,
    [group_id]                                INT            NULL,
    [team_id]                                 INT            NULL,
    [role_id]                                 VARCHAR (500)  NULL,
    [is_hubspot_id_missing]                   BIT            NULL,
    CONSTRAINT [PK_SalesloftUsers_ID] PRIMARY KEY CLUSTERED ([id] ASC)
);

