CREATE TABLE [dbo].[SalesloftAccounts] (
    [id]                       INT            NOT NULL,
    [created_at]               DATETIME       NULL,
    [updated_at]               DATETIME       NULL,
    [archived_at]              DATETIME       NULL,
    [name]                     VARCHAR (500)  NULL,
    [domain]                   VARCHAR (500)  NULL,
    [conversational_name]      VARCHAR (500)  NULL,
    [description]              VARCHAR (500)  NULL,
    [phone]                    VARCHAR (500)  NULL,
    [website]                  VARCHAR (500)  NULL,
    [linkedin_url]             VARCHAR (500)  NULL,
    [twitter_handle]           VARCHAR (500)  NULL,
    [street]                   VARCHAR (500)  NULL,
    [city]                     VARCHAR (500)  NULL,
    [state]                    VARCHAR (500)  NULL,
    [postal_code]              VARCHAR (500)  NULL,
    [country]                  VARCHAR (500)  NULL,
    [locale]                   VARCHAR (500)  NULL,
    [industry]                 VARCHAR (500)  NULL,
    [company_type]             VARCHAR (500)  NULL,
    [founded]                  VARCHAR (500)  NULL,
    [revenue_range]            VARCHAR (500)  NULL,
    [size]                     VARCHAR (500)  NULL,
    [crm_id]                   VARCHAR (500)  NULL,
    [crm_url]                  VARCHAR (500)  NULL,
    [crm_object_type]          VARCHAR (500)  NULL,
    [owner_crm_id]             INT            NULL,
    [last_contacted_at]        DATETIME       NULL,
    [last_contacted_type]      VARCHAR (100)  NULL,
    [do_not_contact]           BIT            NULL,
    [custom_fields]            VARCHAR (1000) NULL,
    [tags]                     VARCHAR (1000) NULL,
    [counts]                   VARCHAR (255)  NULL,
    [owner_id]                 INT            NULL,
    [creator_id]               INT            NULL,
    [last_contacted_by_id]     INT            NULL,
    [last_contacted_person_id] INT            NULL,
    [company_stage_id]         INT            NULL,
    [account_tier_id]          INT            NULL,
    CONSTRAINT [PK_SalesloftAccounts_ID] PRIMARY KEY CLUSTERED ([id] ASC)
);

