CREATE TABLE [dbo].[XML_SupplierProfile] (
    [rn]                     BIGINT         NOT NULL,
    [action]                 VARCHAR (50)   NOT NULL,
    [company_id]             INT            NOT NULL,
    [contact_id]             INT            NULL,
    [address_id]             INT            NULL,
    [publicprofile]          VARCHAR (1000) NULL,
    [address]                XML            NULL,
    [avatar]                 XML            NULL,
    [3dshopview]             XML            NULL,
    [banner]                 XML            NULL,
    [cagecode]               XML            NULL,
    [capabilities]           XML            NULL,
    [certifications]         XML            NULL,
    [date_established]       DATETIME       NULL,
    [description]            XML            NULL,
    [duns]                   XML            NULL,
    [email]                  VARCHAR (150)  NULL,
    [employees]              VARCHAR (150)  NULL,
    [equipment]              XML            NULL,
    [first_name]             VARCHAR (150)  NULL,
    [last_name]              VARCHAR (150)  NULL,
    [gallery]                XML            NULL,
    [industries]             XML            NULL,
    [languages]              XML            NULL,
    [location_manufacturing] XML            NULL,
    [marketplaces]           XML            NULL,
    [mfgverified]            VARCHAR (5)    NULL,
    [name]                   VARCHAR (500)  NULL,
    [tier]                   XML            NULL,
    [phone]                  XML            NULL,
    [owner]                  XML            NULL,
    [reviews]                XML            NULL,
    [source]                 XML            NULL,
    [type]                   XML            NULL,
    [website]                XML            NULL,
    [createddate]            DATETIME       NOT NULL,
    [isprocessed]            BIT            CONSTRAINT [DF__XML_Suppl__ispro__6DE84783] DEFAULT ((0)) NULL,
    [processeddate]          DATETIME       NULL,
    [isincludedinxml]        BIT            CONSTRAINT [DF__XML_Suppl__isinc__6EDC6BBC] DEFAULT ((0)) NULL,
    [includeddate]           DATETIME       NULL,
    CONSTRAINT [PK_XML_SupplierProfile_rn_createddate] PRIMARY KEY CLUSTERED ([rn] ASC, [action] ASC, [company_id] ASC, [createddate] ASC) WITH (FILLFACTOR = 90)
);

