CREATE TABLE [tmp_trans].[revision_data_history_new_values] (
    [data_history_id]                       INT             NULL,
    [RFQName]                               NVARCHAR (2500) NULL,
    [PartId]                                NVARCHAR (2500) NULL,
    [IsRfqPartDefault]                      NVARCHAR (2500) NULL,
    [MinPartQuantity]                       NVARCHAR (2500) NULL,
    [MinPartQuantityUnit]                   NVARCHAR (2500) NULL,
    [IsSpecialCertificationsByManufacture]  NVARCHAR (2500) NULL,
    [CertificateId]                         NVARCHAR (2500) NULL,
    [AwardDate]                             NVARCHAR (2500) NULL,
    [ImportancePrice]                       NVARCHAR (2500) NULL,
    [ImportanceQuality]                     NVARCHAR (2500) NULL,
    [ImportanceSpeed]                       NVARCHAR (2500) NULL,
    [IsRegisterSupplierQuoteTheRfq]         NVARCHAR (2500) NULL,
    [IsSpecialInstructionToManufacturer]    NVARCHAR (2500) NULL,
    [PrefRfqCommunicationMethod]            NVARCHAR (2500) NULL,
    [QuotesNeededBy]                        NVARCHAR (2500) NULL,
    [SpecialInstructionToManufacturer]      NVARCHAR (2500) NULL,
    [RfqPrefManufacturingLocationId]        NVARCHAR (2500) NULL,
    [PaymentTermId]                         NVARCHAR (2500) NULL,
    [PrefNdaType]                           NVARCHAR (2500) NULL,
    [WhoPaysForShipping]                    NVARCHAR (2500) NULL,
    [RfqStatusId]                           NVARCHAR (2500) NULL,
    [QuantityLevel]                         NVARCHAR (2500) NULL,
    [PartQty]                               NVARCHAR (2500) NULL,
    [IsSpecialCertificationsByManufacturer] NVARCHAR (2500) NULL,
    [ShipTo]                                NVARCHAR (2500) NULL,
    [POStatus]                              NVARCHAR (2500) NULL,
    [POPartStatus]                          NVARCHAR (2500) NULL,
    [POCreated]                             NVARCHAR (2500) NULL
);

